{% set name = "scilab" %}
{% set version = "6.1.1" %}
{% set sha256 = "83555679b7d56df4aedad60678d97794cc5aefcda8b57206899016b5702607a4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/opencollab/scilab/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-Fixup-template-with-C-linkage.patch
    - 0001-fix-const-chart-error.patch
    - 0001-Fix-Makefile-syntax.patch
    - 0001-lstdc-fs.patch

build:
  number: 3
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - python
    - make
    - pkg-config
  host:
    - libblas
    - libcblas
    - suitesparse
    - arpack
    - ocaml
    - hdf5 >=1.10,<1.12
    - eigen
    - fftw
    - xorg-libx11
    - ncurses
    - pcre
    - zlib
    - xz
    - libiconv
    - icu
    - libxml2
    - libcurl
    - libmatio
    - gettext  # [not linux]
  run:
    # Missing run_exports
    - {{ pin_compatible('arpack', max_pin='x.x') }}
    - {{ pin_compatible('fftw', max_pin='x.x') }}
    - {{ pin_compatible('openblas', max_pin='x.x') }}
    - {{ pin_compatible('suitesparse', max_pin='x.x') }}
    - {{ pin_compatible('icu', max_pin='x.x') }}
    - {{ pin_compatible('ncurses', max_pin='x.x.x') }}

test:
  commands:
    - scilab-cli -version  # [unix]

about:
  home: https://www.scilab.org/
  license: GPL-2.0-only
  license_family: GPL
  license_file: scilab/COPYING
  summary: 'The Scilab programming language.'
  description: 'Scilab is a  free and open-source, cross-platform numerical computational package and a high-level, numerically oriented programming language.'
  doc_url: https://wiki.scilab.org/Documentation
  dev_url: https://wiki.scilab.org/GetInvolved

extra:
  recipe-maintainers:
    - SylvainCorlay
