appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
travis:
  secure:
    BINSTAR_TOKEN: czRQghOpuW+Cmdp92wwclpEcoXqoPCl1KQSi8KMT7EAEqfbH/SrHTJ5AIjwkbwXDW1ho7XMeGrfOK2CcNyk5Tw/R8XyPKclTKdXh/w2tk8YkmEMfdHRdd1TRcqhkYwCVrdm3v2JNqRmfwgUStjTpmA6nzevnf+Lc6kWSolPqluyybvMCD1cNCbiUQdmJZMvmjheuZsPLx5jPlAzEVhLEse26NEnPiEInH9OGhvVeLEBPvqhalOIK4KJPTJNyZFDaguLXPgMHrwCytHbrWQf2kkPeD9JD4vyt+xoNK7m0PCs0k34GOOz/kmaBTYixrNhouNFC95jq1fGB4kvdwxjeSd6HGWx5WjySLJHzcWTUOQd/uULLRhJpI+g1jEcUzvYXUvzjEORWiqdqKXOey15Yv5SVG37tpt0WTNW6UofASRhTVeILHkELJage1gSptNbgG4FuMhMa7qmwuLJ8kVNoyTDlDnonjvycusLrjhO+OyOYaDpOvmWPMUE2umrLRUzyOFXjJx+3dlpvCFWhGsUep1yQKg3Kh3izg+zbovjcwJMwKrJO/5uz9prINbbiPwPgzlkxJS6wU9BhbpPzpxw1l4JUGvgxJnwsYVp682RdydAKmssZuL+Me9xIGEPVuNyz/hPzlJKXK2AKd7pXUnWUlya7Hv75HRHsnHwxv9NF28o=
